-- AlterTable
ALTER TABLE "Oefening" ADD COLUMN     "bibliotheekId" TEXT;

-- AlterTable
ALTER TABLE "Profiel" ADD COLUMN     "streefdatum" DATE;

-- CreateTable
CREATE TABLE "Voorkeuren" (
    "id" TEXT NOT NULL DEFAULT 'ik',
    "doel" TEXT NOT NULL DEFAULT 'spiermassa',
    "ervaring" TEXT NOT NULL DEFAULT 'gevorderd',
    "dagenPerWeek" INTEGER NOT NULL DEFAULT 3,
    "minutenPerTraining" INTEGER NOT NULL DEFAULT 60,
    "materiaal" TEXT[] DEFAULT ARRAY['dumbbell', 'barbell', 'trap_bar', 'kabel', 'machine', 'stang']::TEXT[],
    "blessures" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "favorieten" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "uitgesloten" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "focus" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "bijgewerktOp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Voorkeuren_pkey" PRIMARY KEY ("id")
);


-- Bestaande oefeningen koppelen aan de bibliotheek (uitleg en foto's), op sleutel uit de catalogus.
UPDATE "Oefening" AS o SET "bibliotheekId" = k.bibliotheek_id
FROM (VALUES
  ('leg_press', 'Leg_Press'),
  ('goblet_squat', 'Goblet_Squat'),
  ('hack_squat', 'Hack_Squat'),
  ('trap_bar_deadlift', 'Trap_Bar_Deadlift'),
  ('back_squat', 'Barbell_Squat'),
  ('box_squat', 'Box_Squat'),
  ('bulgarian_split_squat', 'Split_Squat_with_Dumbbells'),
  ('reverse_lunge', 'Dumbbell_Rear_Lunge'),
  ('step_up', 'Dumbbell_Step_Ups'),
  ('kettlebell_goblet_squat', 'Goblet_Squat'),
  ('bodyweight_squat', 'Bodyweight_Squat'),
  ('romanian_deadlift', 'Romanian_Deadlift'),
  ('db_romanian_deadlift', 'Stiff-Legged_Dumbbell_Deadlift'),
  ('hip_thrust', 'Barbell_Hip_Thrust'),
  ('back_extension_45', 'Hyperextensions_Back_Extensions'),
  ('cable_pull_through', 'Pull_Through'),
  ('deadlift', 'Barbell_Deadlift'),
  ('kettlebell_swing', 'One-Arm_Kettlebell_Swings'),
  ('single_leg_rdl', 'Kettlebell_One-Legged_Deadlift'),
  ('glute_bridge', 'Butt_Lift_Bridge'),
  ('seated_leg_curl', 'Seated_Leg_Curl'),
  ('lying_leg_curl', 'Lying_Leg_Curls'),
  ('ball_leg_curl', 'Ball_Leg_Curl'),
  ('leg_extension', 'Leg_Extensions'),
  ('db_bench_press', 'Dumbbell_Bench_Press'),
  ('machine_chest_press', 'Leverage_Chest_Press'),
  ('incline_db_press', 'Incline_Dumbbell_Press'),
  ('bench_press', 'Barbell_Bench_Press_-_Medium_Grip'),
  ('incline_machine_press', 'Leverage_Incline_Chest_Press'),
  ('kettlebell_floor_press', 'One-Arm_Kettlebell_Floor_Press'),
  ('push_up', 'Pushups'),
  ('incline_push_up', 'Incline_Push-Up'),
  ('dips', 'Dips_-_Chest_Version'),
  ('seated_db_shoulder_press', 'Dumbbell_Shoulder_Press'),
  ('machine_shoulder_press', 'Machine_Shoulder_Military_Press'),
  ('overhead_press', 'Standing_Military_Press'),
  ('kettlebell_press', 'Two-Arm_Kettlebell_Military_Press'),
  ('band_shoulder_press', 'Shoulder_Press_-_With_Bands'),
  ('seated_cable_row', 'Seated_Cable_Rows'),
  ('chest_supported_row', 'Lying_T-Bar_Row'),
  ('one_arm_db_row', 'One-Arm_Dumbbell_Row'),
  ('barbell_row', 'Bent_Over_Barbell_Row'),
  ('kettlebell_row', 'One-Arm_Kettlebell_Row'),
  ('inverted_row', 'Inverted_Row'),
  ('lat_pulldown', 'Wide-Grip_Lat_Pulldown'),
  ('assisted_pull_up', 'Band_Assisted_Pull-Up'),
  ('pull_up', 'Pullups'),
  ('chin_up', 'Chin-Up'),
  ('straight_arm_pulldown', 'Straight-Arm_Pulldown'),
  ('cable_fly', 'Flat_Bench_Cable_Flyes'),
  ('pec_deck', 'Butterfly'),
  ('db_fly', 'Dumbbell_Flyes'),
  ('lateral_raise', 'Side_Lateral_Raise'),
  ('cable_lateral_raise', 'Cable_Seated_Lateral_Raise'),
  ('band_lateral_raise', 'Lateral_Raise_-_With_Bands'),
  ('face_pull', 'Face_Pull'),
  ('reverse_pec_deck', 'Reverse_Machine_Flyes'),
  ('db_reverse_fly', 'Reverse_Flyes'),
  ('band_pull_apart', 'Band_Pull_Apart'),
  ('incline_db_curl', 'Incline_Dumbbell_Curl'),
  ('hammer_curl', 'Hammer_Curls'),
  ('db_curl', 'Dumbbell_Bicep_Curl'),
  ('ez_bar_curl', 'EZ-Bar_Curl'),
  ('cable_curl', 'Standing_Biceps_Cable_Curl'),
  ('rope_hammer_curl', 'Cable_Hammer_Curls_-_Rope_Attachment'),
  ('machine_preacher_curl', 'Machine_Preacher_Curls'),
  ('triceps_pushdown', 'Triceps_Pushdown'),
  ('cable_overhead_triceps_extension', 'Cable_Rope_Overhead_Triceps_Extension'),
  ('db_overhead_triceps_extension', 'Standing_Dumbbell_Triceps_Extension'),
  ('ez_skullcrusher', 'EZ-Bar_Skullcrusher'),
  ('close_grip_bench_press', 'Close-Grip_Barbell_Bench_Press'),
  ('kettlebell_overhead_extension', 'Kettlebell_Overhead_Triceps_Extension'),
  ('close_push_up', 'Push-Ups_-_Close_Triceps_Position'),
  ('standing_calf_raise', 'Standing_Calf_Raises'),
  ('seated_calf_raise', 'Seated_Calf_Raise'),
  ('leg_press_calf_raise', 'Calf_Press_On_The_Leg_Press_Machine'),
  ('db_calf_raise', 'Standing_Dumbbell_Calf_Raise'),
  ('cable_crunch', 'Cable_Crunch'),
  ('dead_bug', 'Dead_Bug'),
  ('ab_crunch_machine', 'Ab_Crunch_Machine'),
  ('reverse_crunch', 'Reverse_Crunch'),
  ('pallof_press', 'Pallof_Press'),
  ('hanging_leg_raise', 'Hanging_Leg_Raise')
) AS k(sleutel, bibliotheek_id)
WHERE o."sleutel" = k.sleutel AND o."bibliotheekId" IS NULL;
