// De basislijst waaruit de schemagenerator kiest: bekende oefeningen die je in vrijwel elke
// sportschool (of thuis) kunt doen, met Nederlandse cues en blessurevlaggen. Waar een oefening
// ook in Benen / Push / Pull staat, is de sleutel gelijk, zodat je geschiedenis meegaat naar een
// nieuw schema. Elke oefening verwijst naar de bibliotheek (Free Exercise DB) voor uitleg en foto's.
//
// Volgorde binnen een patroon = voorkeur. Machines en dumbbells staan vaak vóór de stang: die
// zijn makkelijker te leren en te doseren, en sparen knieën en rug (zie Wetenschap, #personaliseren).

import type { Patroon } from "./bibliotheekOmzetten.js";

export interface CatalogusOefening {
  sleutel: string;
  naam: string;
  bibliotheekId: string;
  patroon: Patroon;
  /** dumbbell | barbell | trap_bar | kabel | machine | lichaamsgewicht | kettlebell | band | overig */
  materiaal: string;
  /** Extra nodig naast het materiaal, bijvoorbeeld een optrekstang. */
  nodig?: string[];
  mechaniek: "compound" | "isolation";
  spierenPrimair: string[];
  spierenSecundair: string[];
  gewichtsstap: number;
  /** Reps tellen per kant. */
  perKant?: boolean;
  knieGevoelig?: boolean;
  /** Bij schouderklachten liever niet (boven je hoofd met een stang, dips). */
  schouderBelastend?: boolean;
  /** Bij lage-rugklachten liever niet (zware stang op of voor de rug). */
  rugBelastend?: boolean;
  /** 1 = geschikt om mee te beginnen, 2 = vraagt wat ervaring, 3 = voor ervaren sporters. */
  niveau: 1 | 2 | 3;
  /** Hoofdlift bij een krachtdoel. */
  hoofdlift?: boolean;
  cue: string;
}

export const CATALOGUS: CatalogusOefening[] = [
  // ---------- Kniedominant ----------
  { sleutel: "leg_press", naam: "Leg press", bibliotheekId: "Leg_Press", patroon: "knie_dominant", materiaal: "machine", mechaniek: "compound", spierenPrimair: ["quads", "glutes"], spierenSecundair: ["adductors"], gewichtsstap: 5, knieGevoelig: true, niveau: 1, cue: "Voeten midden op het platform, zo diep als pijnvrij lukt, knieën niet op slot." },
  { sleutel: "goblet_squat", naam: "Goblet squat", bibliotheekId: "Goblet_Squat", patroon: "knie_dominant", materiaal: "dumbbell", mechaniek: "compound", spierenPrimair: ["quads", "glutes"], spierenSecundair: ["abs"], gewichtsstap: 2, knieGevoelig: true, niveau: 1, cue: "Dumbbell tegen je borst, ellebogen tussen je knieën, 3 sec zakken." },
  { sleutel: "hack_squat", naam: "Hack squat", bibliotheekId: "Hack_Squat", patroon: "knie_dominant", materiaal: "machine", mechaniek: "compound", spierenPrimair: ["quads", "glutes"], spierenSecundair: [], gewichtsstap: 5, knieGevoelig: true, niveau: 1, cue: "Rug tegen het kussen, zakken zo ver als pijnvrij lukt." },
  { sleutel: "trap_bar_deadlift", naam: "Trap bar deadlift", bibliotheekId: "Trap_Bar_Deadlift", patroon: "knie_dominant", materiaal: "trap_bar", mechaniek: "compound", spierenPrimair: ["quads", "glutes"], spierenSecundair: ["hamstrings", "upper_back", "forearms"], gewichtsstap: 5, knieGevoelig: true, rugBelastend: true, niveau: 1, hoofdlift: true, cue: "Heupen en knieën tegelijk strekken, rug neutraal, 3 sec zakken." },
  { sleutel: "back_squat", naam: "Back squat", bibliotheekId: "Barbell_Squat", patroon: "knie_dominant", materiaal: "barbell", mechaniek: "compound", spierenPrimair: ["quads", "glutes"], spierenSecundair: ["adductors", "lower_back"], gewichtsstap: 2.5, knieGevoelig: true, rugBelastend: true, niveau: 2, hoofdlift: true, cue: "Stang op je bovenrug, borst omhoog, knieën in de richting van je tenen." },
  { sleutel: "box_squat", naam: "Box squat", bibliotheekId: "Box_Squat", patroon: "knie_dominant", materiaal: "barbell", mechaniek: "compound", spierenPrimair: ["quads", "glutes"], spierenSecundair: ["hamstrings", "adductors"], gewichtsstap: 2.5, knieGevoelig: true, rugBelastend: true, niveau: 2, cue: "Gecontroleerd zitten op de box, even stil, dan omhoog. De box bepaalt je diepte." },
  { sleutel: "bulgarian_split_squat", naam: "Bulgarian split squat", bibliotheekId: "Split_Squat_with_Dumbbells", patroon: "knie_dominant", materiaal: "dumbbell", mechaniek: "compound", spierenPrimair: ["quads", "glutes"], spierenSecundair: ["adductors"], gewichtsstap: 2, perKant: true, knieGevoelig: true, niveau: 2, cue: "Voorste voet ver genoeg naar voren, 3 sec zakken." },
  { sleutel: "reverse_lunge", naam: "Reverse lunge", bibliotheekId: "Dumbbell_Rear_Lunge", patroon: "knie_dominant", materiaal: "dumbbell", mechaniek: "compound", spierenPrimair: ["quads", "glutes"], spierenSecundair: ["adductors"], gewichtsstap: 2, perKant: true, knieGevoelig: true, niveau: 1, cue: "Stap naar achteren, voorste knie boven je voet, rustig zakken." },
  { sleutel: "step_up", naam: "Step-up", bibliotheekId: "Dumbbell_Step_Ups", patroon: "knie_dominant", materiaal: "dumbbell", mechaniek: "compound", spierenPrimair: ["quads", "glutes"], spierenSecundair: [], gewichtsstap: 2, perKant: true, knieGevoelig: true, niveau: 1, cue: "Kniehoge box, duw af met het voorste been, niet met je achterste voet." },
  { sleutel: "kettlebell_goblet_squat", naam: "Kettlebell goblet squat", bibliotheekId: "Goblet_Squat", patroon: "knie_dominant", materiaal: "kettlebell", mechaniek: "compound", spierenPrimair: ["quads", "glutes"], spierenSecundair: ["abs"], gewichtsstap: 4, knieGevoelig: true, niveau: 1, cue: "Kettlebell bij de hoorns tegen je borst, rustig zakken." },
  { sleutel: "bodyweight_squat", naam: "Squat zonder gewicht", bibliotheekId: "Bodyweight_Squat", patroon: "knie_dominant", materiaal: "lichaamsgewicht", mechaniek: "compound", spierenPrimair: ["quads", "glutes"], spierenSecundair: [], gewichtsstap: 0, knieGevoelig: true, niveau: 1, cue: "3 sec zakken, 1 sec pauze onderin. Te makkelijk? Neem een tas of dumbbell." },

  // ---------- Heupdominant ----------
  { sleutel: "romanian_deadlift", naam: "Romanian deadlift", bibliotheekId: "Romanian_Deadlift", patroon: "heup_dominant", materiaal: "barbell", mechaniek: "compound", spierenPrimair: ["hamstrings", "glutes"], spierenSecundair: ["lower_back", "forearms"], gewichtsstap: 2.5, rugBelastend: true, niveau: 2, hoofdlift: true, cue: "Heupen naar achteren, stang langs de benen, stop bij rek in de hamstrings." },
  { sleutel: "db_romanian_deadlift", naam: "Dumbbell Romanian deadlift", bibliotheekId: "Stiff-Legged_Dumbbell_Deadlift", patroon: "heup_dominant", materiaal: "dumbbell", mechaniek: "compound", spierenPrimair: ["hamstrings", "glutes"], spierenSecundair: ["lower_back", "forearms"], gewichtsstap: 2, niveau: 1, cue: "Heupen naar achteren, dumbbells langs je benen, rug neutraal." },
  { sleutel: "hip_thrust", naam: "Hip thrust", bibliotheekId: "Barbell_Hip_Thrust", patroon: "heup_dominant", materiaal: "barbell", mechaniek: "compound", spierenPrimair: ["glutes"], spierenSecundair: ["hamstrings"], gewichtsstap: 2.5, niveau: 1, cue: "Bovenrug op de bank, kin licht naar je borst, bovenin 1 sec knijpen." },
  { sleutel: "back_extension_45", naam: "45° back extension", bibliotheekId: "Hyperextensions_Back_Extensions", patroon: "heup_dominant", materiaal: "lichaamsgewicht", mechaniek: "compound", spierenPrimair: ["hamstrings", "glutes"], spierenSecundair: ["lower_back"], gewichtsstap: 2.5, niveau: 1, cue: "Buig in je heupen, niet in je rug. Te licht? Houd een schijf vast." },
  { sleutel: "cable_pull_through", naam: "Cable pull-through", bibliotheekId: "Pull_Through", patroon: "heup_dominant", materiaal: "kabel", mechaniek: "compound", spierenPrimair: ["glutes", "hamstrings"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Met je rug naar de kabel, heupen naar achteren, bovenin billen aanspannen." },
  { sleutel: "deadlift", naam: "Deadlift", bibliotheekId: "Barbell_Deadlift", patroon: "heup_dominant", materiaal: "barbell", mechaniek: "compound", spierenPrimair: ["hamstrings", "glutes"], spierenSecundair: ["quads", "lower_back", "upper_back", "forearms"], gewichtsstap: 2.5, rugBelastend: true, niveau: 2, hoofdlift: true, cue: "Stang tegen je schenen, borst omhoog, duw de vloer weg." },
  { sleutel: "kettlebell_swing", naam: "Kettlebell swing", bibliotheekId: "One-Arm_Kettlebell_Swings", patroon: "heup_dominant", materiaal: "kettlebell", mechaniek: "compound", spierenPrimair: ["glutes", "hamstrings"], spierenSecundair: ["lower_back", "abs"], gewichtsstap: 4, rugBelastend: true, niveau: 2, cue: "Explosief uit je heupen, armen hangen los. Geen squat." },
  { sleutel: "single_leg_rdl", naam: "Single-leg Romanian deadlift", bibliotheekId: "Kettlebell_One-Legged_Deadlift", patroon: "heup_dominant", materiaal: "dumbbell", mechaniek: "compound", spierenPrimair: ["hamstrings", "glutes"], spierenSecundair: ["lower_back"], gewichtsstap: 2, perKant: true, niveau: 2, cue: "Heup en achterste been als één plank naar achteren, heupen recht." },
  { sleutel: "glute_bridge", naam: "Glute bridge", bibliotheekId: "Butt_Lift_Bridge", patroon: "heup_dominant", materiaal: "lichaamsgewicht", mechaniek: "compound", spierenPrimair: ["glutes"], spierenSecundair: ["hamstrings"], gewichtsstap: 0, niveau: 1, cue: "Op je rug, hielen dicht bij je billen, bovenin 2 sec knijpen." },

  // ---------- Hamstrings en voorkant bovenbeen apart ----------
  { sleutel: "seated_leg_curl", naam: "Seated leg curl", bibliotheekId: "Seated_Leg_Curl", patroon: "hamstring_curl", materiaal: "machine", mechaniek: "isolation", spierenPrimair: ["hamstrings"], spierenSecundair: ["calves"], gewichtsstap: 2.5, niveau: 1, cue: "Heupen tegen de leuning, gecontroleerd terug." },
  { sleutel: "lying_leg_curl", naam: "Lying leg curl", bibliotheekId: "Lying_Leg_Curls", patroon: "hamstring_curl", materiaal: "machine", mechaniek: "isolation", spierenPrimair: ["hamstrings"], spierenSecundair: ["calves"], gewichtsstap: 2.5, niveau: 1, cue: "Heupen op het kussen, 3 sec terug." },
  { sleutel: "ball_leg_curl", naam: "Leg curl op een fitnessbal", bibliotheekId: "Ball_Leg_Curl", patroon: "hamstring_curl", materiaal: "overig", mechaniek: "isolation", spierenPrimair: ["hamstrings"], spierenSecundair: ["glutes"], gewichtsstap: 0, niveau: 1, cue: "Heupen hoog houden terwijl je de bal naar je toe rolt." },
  { sleutel: "leg_extension", naam: "Leg extension", bibliotheekId: "Leg_Extensions", patroon: "quad_isolatie", materiaal: "machine", mechaniek: "isolation", spierenPrimair: ["quads"], spierenSecundair: [], gewichtsstap: 2.5, knieGevoelig: true, niveau: 1, cue: "3 sec zakken, bovenin 1 sec vasthouden." },

  // ---------- Horizontaal duwen ----------
  { sleutel: "db_bench_press", naam: "Dumbbell bench press", bibliotheekId: "Dumbbell_Bench_Press", patroon: "horizontaal_duwen", materiaal: "dumbbell", mechaniek: "compound", spierenPrimair: ["chest"], spierenSecundair: ["front_delts", "triceps"], gewichtsstap: 2, niveau: 1, cue: "Schouderbladen naar achter en omlaag, ellebogen ~45°." },
  { sleutel: "machine_chest_press", naam: "Machine chest press", bibliotheekId: "Leverage_Chest_Press", patroon: "horizontaal_duwen", materiaal: "machine", mechaniek: "compound", spierenPrimair: ["chest"], spierenSecundair: ["front_delts", "triceps"], gewichtsstap: 2.5, niveau: 1, cue: "Handgrepen op borsthoogte, schouderbladen tegen de leuning." },
  { sleutel: "incline_db_press", naam: "Incline dumbbell press", bibliotheekId: "Incline_Dumbbell_Press", patroon: "horizontaal_duwen", materiaal: "dumbbell", mechaniek: "compound", spierenPrimair: ["chest", "front_delts"], spierenSecundair: ["triceps"], gewichtsstap: 2, niveau: 1, cue: "Bank op 30°." },
  { sleutel: "bench_press", naam: "Bench press", bibliotheekId: "Barbell_Bench_Press_-_Medium_Grip", patroon: "horizontaal_duwen", materiaal: "barbell", mechaniek: "compound", spierenPrimair: ["chest"], spierenSecundair: ["front_delts", "triceps"], gewichtsstap: 2.5, schouderBelastend: true, niveau: 2, hoofdlift: true, cue: "Voeten stevig neer, stang naar je onderste borst, ellebogen ~45°." },
  { sleutel: "incline_machine_press", naam: "Incline machine press", bibliotheekId: "Leverage_Incline_Chest_Press", patroon: "horizontaal_duwen", materiaal: "machine", mechaniek: "compound", spierenPrimair: ["chest", "front_delts"], spierenSecundair: ["triceps"], gewichtsstap: 2.5, niveau: 1, cue: "Stoel zo dat de handgrepen op borsthoogte zitten." },
  { sleutel: "kettlebell_floor_press", naam: "Kettlebell floor press", bibliotheekId: "One-Arm_Kettlebell_Floor_Press", patroon: "horizontaal_duwen", materiaal: "kettlebell", mechaniek: "compound", spierenPrimair: ["chest"], spierenSecundair: ["triceps", "front_delts"], gewichtsstap: 4, perKant: true, niveau: 1, cue: "Op je rug, bovenarm raakt de vloer, dan duwen." },
  { sleutel: "push_up", naam: "Push-up", bibliotheekId: "Pushups", patroon: "horizontaal_duwen", materiaal: "lichaamsgewicht", mechaniek: "compound", spierenPrimair: ["chest"], spierenSecundair: ["front_delts", "triceps"], gewichtsstap: 0, niveau: 1, cue: "Lichaam als een plank, borst tot vlak boven de vloer." },
  { sleutel: "incline_push_up", naam: "Push-up op een bank", bibliotheekId: "Incline_Push-Up", patroon: "horizontaal_duwen", materiaal: "lichaamsgewicht", mechaniek: "compound", spierenPrimair: ["chest"], spierenSecundair: ["front_delts", "triceps"], gewichtsstap: 0, niveau: 1, cue: "Handen op een bank: lichter dan een gewone push-up." },
  { sleutel: "dips", naam: "Dips", bibliotheekId: "Dips_-_Chest_Version", patroon: "horizontaal_duwen", materiaal: "lichaamsgewicht", nodig: ["stang"], mechaniek: "compound", spierenPrimair: ["chest", "triceps"], spierenSecundair: ["front_delts"], gewichtsstap: 2.5, schouderBelastend: true, niveau: 2, cue: "Licht voorover, zak tot je schouders net onder je ellebogen zijn, pijnvrij." },

  // ---------- Verticaal duwen ----------
  { sleutel: "seated_db_shoulder_press", naam: "Seated dumbbell shoulder press", bibliotheekId: "Dumbbell_Shoulder_Press", patroon: "verticaal_duwen", materiaal: "dumbbell", mechaniek: "compound", spierenPrimair: ["front_delts"], spierenSecundair: ["side_delts", "triceps"], gewichtsstap: 2, niveau: 1, cue: "Rug tegen de leuning, niet doorbuigen." },
  { sleutel: "machine_shoulder_press", naam: "Machine shoulder press", bibliotheekId: "Machine_Shoulder_Military_Press", patroon: "verticaal_duwen", materiaal: "machine", mechaniek: "compound", spierenPrimair: ["front_delts"], spierenSecundair: ["side_delts", "triceps"], gewichtsstap: 2.5, niveau: 1, cue: "Handgrepen op schouderhoogte, duw zonder je onderrug hol te trekken." },
  { sleutel: "overhead_press", naam: "Overhead press", bibliotheekId: "Standing_Military_Press", patroon: "verticaal_duwen", materiaal: "barbell", mechaniek: "compound", spierenPrimair: ["front_delts"], spierenSecundair: ["side_delts", "triceps", "upper_back"], gewichtsstap: 2.5, schouderBelastend: true, rugBelastend: true, niveau: 2, hoofdlift: true, cue: "Billen en buik aan, stang langs je gezicht omhoog, hoofd door je armen." },
  { sleutel: "kettlebell_press", naam: "Kettlebell press", bibliotheekId: "Two-Arm_Kettlebell_Military_Press", patroon: "verticaal_duwen", materiaal: "kettlebell", mechaniek: "compound", spierenPrimair: ["front_delts"], spierenSecundair: ["side_delts", "triceps"], gewichtsstap: 4, schouderBelastend: true, niveau: 2, cue: "Kettlebells op schouderhoogte, omhoog duwen zonder achterover te leunen." },
  { sleutel: "band_shoulder_press", naam: "Shoulder press met band", bibliotheekId: "Shoulder_Press_-_With_Bands", patroon: "verticaal_duwen", materiaal: "band", mechaniek: "compound", spierenPrimair: ["front_delts"], spierenSecundair: ["side_delts", "triceps"], gewichtsstap: 0, niveau: 1, cue: "Sta op de band, duw rustig omhoog en laat langzaam zakken." },

  // ---------- Horizontaal trekken ----------
  { sleutel: "seated_cable_row", naam: "Seated cable row", bibliotheekId: "Seated_Cable_Rows", patroon: "horizontaal_trekken", materiaal: "kabel", mechaniek: "compound", spierenPrimair: ["upper_back", "lats"], spierenSecundair: ["biceps", "rear_delts"], gewichtsstap: 2.5, niveau: 1, cue: "Eerst schouderbladen samen, niet zwaaien met je rug." },
  { sleutel: "chest_supported_row", naam: "Chest-supported row", bibliotheekId: "Lying_T-Bar_Row", patroon: "horizontaal_trekken", materiaal: "machine", mechaniek: "compound", spierenPrimair: ["upper_back", "lats"], spierenSecundair: ["biceps", "rear_delts"], gewichtsstap: 2.5, niveau: 1, cue: "Borst tegen het kussen, ellebogen langs je lichaam naar achteren." },
  { sleutel: "one_arm_db_row", naam: "One-arm dumbbell row", bibliotheekId: "One-Arm_Dumbbell_Row", patroon: "horizontaal_trekken", materiaal: "dumbbell", mechaniek: "compound", spierenPrimair: ["upper_back", "lats"], spierenSecundair: ["biceps", "rear_delts"], gewichtsstap: 2, perKant: true, niveau: 1, cue: "Hand en knie op de bank, trek de dumbbell naar je heup." },
  { sleutel: "barbell_row", naam: "Barbell row", bibliotheekId: "Bent_Over_Barbell_Row", patroon: "horizontaal_trekken", materiaal: "barbell", mechaniek: "compound", spierenPrimair: ["upper_back", "lats"], spierenSecundair: ["biceps", "rear_delts", "lower_back"], gewichtsstap: 2.5, rugBelastend: true, niveau: 2, hoofdlift: true, cue: "Romp ~45° voorover, rug neutraal, stang naar je navel." },
  { sleutel: "kettlebell_row", naam: "Kettlebell row", bibliotheekId: "One-Arm_Kettlebell_Row", patroon: "horizontaal_trekken", materiaal: "kettlebell", mechaniek: "compound", spierenPrimair: ["upper_back", "lats"], spierenSecundair: ["biceps", "rear_delts"], gewichtsstap: 4, perKant: true, niveau: 1, cue: "Steun op een bank of je knie, trek naar je heup." },
  { sleutel: "inverted_row", naam: "Inverted row", bibliotheekId: "Inverted_Row", patroon: "horizontaal_trekken", materiaal: "lichaamsgewicht", nodig: ["stang"], mechaniek: "compound", spierenPrimair: ["upper_back", "lats"], spierenSecundair: ["biceps", "rear_delts"], gewichtsstap: 0, niveau: 1, cue: "Lichaam als een plank onder een stang, borst naar de stang." },

  // ---------- Verticaal trekken ----------
  { sleutel: "lat_pulldown", naam: "Lat pulldown", bibliotheekId: "Wide-Grip_Lat_Pulldown", patroon: "verticaal_trekken", materiaal: "kabel", mechaniek: "compound", spierenPrimair: ["lats"], spierenSecundair: ["biceps", "upper_back"], gewichtsstap: 2.5, niveau: 1, cue: "Borst omhoog, ellebogen naar je zij." },
  { sleutel: "assisted_pull_up", naam: "(Assisted) pull-up", bibliotheekId: "Band_Assisted_Pull-Up", patroon: "verticaal_trekken", materiaal: "machine", mechaniek: "compound", spierenPrimair: ["lats"], spierenSecundair: ["biceps", "upper_back"], gewichtsstap: 5, niveau: 1, cue: "Volledig hangen onderin, kin boven de stang." },
  { sleutel: "pull_up", naam: "Pull-up", bibliotheekId: "Pullups", patroon: "verticaal_trekken", materiaal: "lichaamsgewicht", nodig: ["stang"], mechaniek: "compound", spierenPrimair: ["lats"], spierenSecundair: ["biceps", "upper_back"], gewichtsstap: 2.5, niveau: 2, hoofdlift: true, cue: "Volledig hangen onderin, borst naar de stang." },
  { sleutel: "chin_up", naam: "Chin-up", bibliotheekId: "Chin-Up", patroon: "verticaal_trekken", materiaal: "lichaamsgewicht", nodig: ["stang"], mechaniek: "compound", spierenPrimair: ["lats", "biceps"], spierenSecundair: ["upper_back"], gewichtsstap: 2.5, niveau: 2, cue: "Handpalmen naar je toe, kin boven de stang, rustig zakken." },
  { sleutel: "db_pullover", naam: "Dumbbell pullover", bibliotheekId: "Straight-Arm_Dumbbell_Pullover", patroon: "verticaal_trekken", materiaal: "dumbbell", mechaniek: "isolation", spierenPrimair: ["lats"], spierenSecundair: ["chest", "triceps"], gewichtsstap: 2, niveau: 1, cue: "Dwars op een bank, dumbbell in een boog achter je hoofd tot je rek voelt." },
  { sleutel: "straight_arm_pulldown", naam: "Straight-arm pulldown", bibliotheekId: "Straight-Arm_Pulldown", patroon: "verticaal_trekken", materiaal: "kabel", mechaniek: "isolation", spierenPrimair: ["lats"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Armen bijna gestrekt, stang in een boog naar je dijen." },

  // ---------- Borst apart ----------
  { sleutel: "cable_fly", naam: "Cable fly", bibliotheekId: "Flat_Bench_Cable_Flyes", patroon: "borst_isolatie", materiaal: "kabel", mechaniek: "isolation", spierenPrimair: ["chest"], spierenSecundair: ["front_delts"], gewichtsstap: 2.5, niveau: 1, cue: "Lichte buiging in de ellebogen, focus op de rek." },
  { sleutel: "pec_deck", naam: "Pec deck", bibliotheekId: "Butterfly", patroon: "borst_isolatie", materiaal: "machine", mechaniek: "isolation", spierenPrimair: ["chest"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Ellebogen op schouderhoogte, 3 sec terug." },
  { sleutel: "db_fly", naam: "Dumbbell fly", bibliotheekId: "Dumbbell_Flyes", patroon: "borst_isolatie", materiaal: "dumbbell", mechaniek: "isolation", spierenPrimair: ["chest"], spierenSecundair: ["front_delts"], gewichtsstap: 1, niveau: 1, cue: "Licht gewicht, ellebogen licht gebogen, zak tot je rek voelt." },

  // ---------- Zijkant schouders ----------
  { sleutel: "lateral_raise", naam: "Lateral raise", bibliotheekId: "Side_Lateral_Raise", patroon: "zijkant_schouder", materiaal: "dumbbell", mechaniek: "isolation", spierenPrimair: ["side_delts"], spierenSecundair: [], gewichtsstap: 1, niveau: 1, cue: "Licht gewicht, leid met de ellebogen tot schouderhoogte." },
  { sleutel: "cable_lateral_raise", naam: "Cable lateral raise", bibliotheekId: "Cable_Seated_Lateral_Raise", patroon: "zijkant_schouder", materiaal: "kabel", mechaniek: "isolation", spierenPrimair: ["side_delts"], spierenSecundair: [], gewichtsstap: 1.25, perKant: true, niveau: 1, cue: "Kabel achter je lichaam langs, rustig tot schouderhoogte." },
  { sleutel: "band_lateral_raise", naam: "Lateral raise met band", bibliotheekId: "Lateral_Raise_-_With_Bands", patroon: "zijkant_schouder", materiaal: "band", mechaniek: "isolation", spierenPrimair: ["side_delts"], spierenSecundair: [], gewichtsstap: 0, niveau: 1, cue: "Sta op de band, armen zijwaarts tot schouderhoogte." },

  // ---------- Achterkant schouders ----------
  { sleutel: "face_pull", naam: "Face pull", bibliotheekId: "Face_Pull", patroon: "achterkant_schouder", materiaal: "kabel", mechaniek: "isolation", spierenPrimair: ["rear_delts", "upper_back"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Touw naar je voorhoofd, ellebogen hoog." },
  { sleutel: "reverse_pec_deck", naam: "Reverse pec deck", bibliotheekId: "Reverse_Machine_Flyes", patroon: "achterkant_schouder", materiaal: "machine", mechaniek: "isolation", spierenPrimair: ["rear_delts", "upper_back"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Armen bijna gestrekt, breed naar achteren, niet met je rug." },
  { sleutel: "db_reverse_fly", naam: "Dumbbell reverse fly", bibliotheekId: "Reverse_Flyes", patroon: "achterkant_schouder", materiaal: "dumbbell", mechaniek: "isolation", spierenPrimair: ["rear_delts", "upper_back"], spierenSecundair: [], gewichtsstap: 1, niveau: 1, cue: "Voorover of met je borst op een schuine bank, licht gewicht." },
  { sleutel: "band_pull_apart", naam: "Band pull-apart", bibliotheekId: "Band_Pull_Apart", patroon: "achterkant_schouder", materiaal: "band", mechaniek: "isolation", spierenPrimair: ["rear_delts", "upper_back"], spierenSecundair: [], gewichtsstap: 0, niveau: 1, cue: "Band op borsthoogte uit elkaar trekken, schouderbladen samen." },

  // ---------- Biceps ----------
  { sleutel: "incline_db_curl", naam: "Incline dumbbell curl", bibliotheekId: "Incline_Dumbbell_Curl", patroon: "biceps", materiaal: "dumbbell", mechaniek: "isolation", spierenPrimair: ["biceps"], spierenSecundair: [], gewichtsstap: 1, niveau: 1, cue: "Bank op 45°, armen hangen achter je lichaam." },
  { sleutel: "hammer_curl", naam: "Hammer curl", bibliotheekId: "Hammer_Curls", patroon: "biceps", materiaal: "dumbbell", mechaniek: "isolation", spierenPrimair: ["biceps", "forearms"], spierenSecundair: [], gewichtsstap: 1, niveau: 1, cue: "Duimen omhoog, ellebogen stil." },
  { sleutel: "db_curl", naam: "Dumbbell curl", bibliotheekId: "Dumbbell_Bicep_Curl", patroon: "biceps", materiaal: "dumbbell", mechaniek: "isolation", spierenPrimair: ["biceps"], spierenSecundair: ["forearms"], gewichtsstap: 1, niveau: 1, cue: "Ellebogen langs je zij, rustig zakken tot je armen gestrekt zijn." },
  { sleutel: "ez_bar_curl", naam: "EZ-bar curl", bibliotheekId: "EZ-Bar_Curl", patroon: "biceps", materiaal: "barbell", mechaniek: "isolation", spierenPrimair: ["biceps"], spierenSecundair: ["forearms"], gewichtsstap: 2.5, niveau: 1, cue: "Niet zwaaien, ellebogen blijven op hun plek." },
  { sleutel: "cable_curl", naam: "Cable curl", bibliotheekId: "Standing_Biceps_Cable_Curl", patroon: "biceps", materiaal: "kabel", mechaniek: "isolation", spierenPrimair: ["biceps"], spierenSecundair: ["forearms"], gewichtsstap: 2.5, niveau: 1, cue: "Ellebogen stil, bovenin 1 sec knijpen." },
  { sleutel: "rope_hammer_curl", naam: "Cable rope hammer curl", bibliotheekId: "Cable_Hammer_Curls_-_Rope_Attachment", patroon: "biceps", materiaal: "kabel", mechaniek: "isolation", spierenPrimair: ["biceps", "forearms"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Duimen omhoog, ellebogen langs je zij." },
  { sleutel: "machine_preacher_curl", naam: "Machine preacher curl", bibliotheekId: "Machine_Preacher_Curls", patroon: "biceps", materiaal: "machine", mechaniek: "isolation", spierenPrimair: ["biceps"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Bovenarmen plat op het kussen, onderin bijna gestrekt." },

  // ---------- Triceps ----------
  { sleutel: "triceps_pushdown", naam: "Triceps pushdown", bibliotheekId: "Triceps_Pushdown", patroon: "triceps", materiaal: "kabel", mechaniek: "isolation", spierenPrimair: ["triceps"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Ellebogen tegen je zij, onderin volledig strekken." },
  { sleutel: "cable_overhead_triceps_extension", naam: "Cable overhead triceps extension", bibliotheekId: "Cable_Rope_Overhead_Triceps_Extension", patroon: "triceps", materiaal: "kabel", mechaniek: "isolation", spierenPrimair: ["triceps"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Ellebogen naast je hoofd, volledige rek." },
  { sleutel: "db_overhead_triceps_extension", naam: "Dumbbell overhead triceps extension", bibliotheekId: "Standing_Dumbbell_Triceps_Extension", patroon: "triceps", materiaal: "dumbbell", mechaniek: "isolation", spierenPrimair: ["triceps"], spierenSecundair: [], gewichtsstap: 2, niveau: 1, cue: "Eén dumbbell met twee handen achter je hoofd, ellebogen naar voren." },
  { sleutel: "ez_skullcrusher", naam: "EZ-bar skullcrusher", bibliotheekId: "EZ-Bar_Skullcrusher", patroon: "triceps", materiaal: "barbell", mechaniek: "isolation", spierenPrimair: ["triceps"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 2, cue: "Stang naar je voorhoofd of net erachter, ellebogen wijzen omhoog." },
  { sleutel: "close_grip_bench_press", naam: "Close-grip bench press", bibliotheekId: "Close-Grip_Barbell_Bench_Press", patroon: "triceps", materiaal: "barbell", mechaniek: "compound", spierenPrimair: ["triceps"], spierenSecundair: ["chest", "front_delts"], gewichtsstap: 2.5, niveau: 2, cue: "Handen op schouderbreedte, ellebogen langs je lichaam." },
  { sleutel: "kettlebell_overhead_extension", naam: "Kettlebell overhead extension", bibliotheekId: "Kettlebell_Overhead_Triceps_Extension", patroon: "triceps", materiaal: "kettlebell", mechaniek: "isolation", spierenPrimair: ["triceps"], spierenSecundair: [], gewichtsstap: 4, niveau: 1, cue: "Kettlebell achter je hoofd, ellebogen naar voren." },
  { sleutel: "close_push_up", naam: "Smalle push-up", bibliotheekId: "Push-Ups_-_Close_Triceps_Position", patroon: "triceps", materiaal: "lichaamsgewicht", mechaniek: "compound", spierenPrimair: ["triceps"], spierenSecundair: ["chest", "front_delts"], gewichtsstap: 0, niveau: 1, cue: "Handen onder je schouders, ellebogen langs je lichaam." },

  // ---------- Kuiten ----------
  { sleutel: "standing_calf_raise", naam: "Staande kuitraise", bibliotheekId: "Standing_Calf_Raises", patroon: "kuiten", materiaal: "machine", mechaniek: "isolation", spierenPrimair: ["calves"], spierenSecundair: [], gewichtsstap: 5, niveau: 1, cue: "Volledige rek onderin, 1 sec pauze." },
  { sleutel: "seated_calf_raise", naam: "Zittende kuitraise", bibliotheekId: "Seated_Calf_Raise", patroon: "kuiten", materiaal: "machine", mechaniek: "isolation", spierenPrimair: ["calves"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Volledige rek, 1 sec pauze bovenin." },
  { sleutel: "leg_press_calf_raise", naam: "Kuitraise op leg press", bibliotheekId: "Calf_Press_On_The_Leg_Press_Machine", patroon: "kuiten", materiaal: "machine", mechaniek: "isolation", spierenPrimair: ["calves"], spierenSecundair: [], gewichtsstap: 5, niveau: 1, cue: "Alleen je voorvoeten op het platform, knieën bijna gestrekt." },
  { sleutel: "db_calf_raise", naam: "Kuitraise met dumbbell", bibliotheekId: "Standing_Dumbbell_Calf_Raise", patroon: "kuiten", materiaal: "dumbbell", mechaniek: "isolation", spierenPrimair: ["calves"], spierenSecundair: [], gewichtsstap: 2, perKant: true, niveau: 1, cue: "Op één been op een traptree, dumbbell in de andere hand, volledige rek." },

  // ---------- Buik ----------
  { sleutel: "cable_crunch", naam: "Cable crunch", bibliotheekId: "Cable_Crunch", patroon: "buik", materiaal: "kabel", mechaniek: "isolation", spierenPrimair: ["abs"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Rol je romp op, heupen blijven stil." },
  { sleutel: "dead_bug", naam: "Dead bug", bibliotheekId: "Dead_Bug", patroon: "buik", materiaal: "lichaamsgewicht", mechaniek: "isolation", spierenPrimair: ["abs"], spierenSecundair: [], gewichtsstap: 0, perKant: true, niveau: 1, cue: "Onderrug plat op de vloer, langzaam uitstrekken." },
  { sleutel: "ab_crunch_machine", naam: "Crunch-machine", bibliotheekId: "Ab_Crunch_Machine", patroon: "buik", materiaal: "machine", mechaniek: "isolation", spierenPrimair: ["abs"], spierenSecundair: [], gewichtsstap: 2.5, niveau: 1, cue: "Rol je romp op, niet trekken met je armen." },
  { sleutel: "reverse_crunch", naam: "Reverse crunch", bibliotheekId: "Reverse_Crunch", patroon: "buik", materiaal: "lichaamsgewicht", mechaniek: "isolation", spierenPrimair: ["abs"], spierenSecundair: [], gewichtsstap: 0, niveau: 1, cue: "Krul je bekken op naar je borst, rustig terug." },
  { sleutel: "pallof_press", naam: "Pallof press", bibliotheekId: "Pallof_Press", patroon: "buik", materiaal: "kabel", mechaniek: "isolation", spierenPrimair: ["abs"], spierenSecundair: [], gewichtsstap: 2.5, perKant: true, niveau: 1, cue: "Zijwaarts naast de kabel, handen recht vooruit duwen zonder te draaien." },
  { sleutel: "hanging_leg_raise", naam: "Hanging leg raise", bibliotheekId: "Hanging_Leg_Raise", patroon: "buik", materiaal: "lichaamsgewicht", nodig: ["stang"], mechaniek: "isolation", spierenPrimair: ["abs"], spierenSecundair: [], gewichtsstap: 0, niveau: 3, cue: "Niet zwaaien, bekken oprollen, knieën naar je borst." },
];

export const CATALOGUS_PER_SLEUTEL = new Map(CATALOGUS.map((o) => [o.sleutel, o]));
